%Detection and tracking gui
fi.L=hf.Position(1);
fi.B=hf.Position(2);
fi.W=hf.Position(3);
fi.H=hf.Position(4);

buff.w=max([20,0.025*fi.W]);
buff.h=60;

minbuff_h=6;
stdbuff_h=2*minbuff_h;
elementsep_h=stdbuff_h;
txtbx_h=25;
rbtn_h=22;
pushbutton_h=30;
txt_h=20;

%Heights
view_relintrb_h=stdbuff_h + rbtn_h + minbuff_h...
    + rbtn_h + minbuff_h + stdbuff_h;

view_chnrb_h=stdbuff_h + rbtn_h + minbuff_h...
    + rbtn_h + minbuff_h...
    + rbtn_h + minbuff_h + stdbuff_h;

viewpanel_h =...
    stdbuff_h...
    + elementsep_h...
    + txtbx_h + txt_h + minbuff_h...
    + elementsep_h...
    + txtbx_h + txt_h + minbuff_h...
    + elementsep_h...
    + view_chnrb_h...
    + elementsep_h...
    + view_relintrb_h...
    + stdbuff_h;

operationpanel_mode_h = stdbuff_h...
    + rbtn_h + minbuff_h...
    + rbtn_h + minbuff_h...
    + rbtn_h + stdbuff_h;

operationpanel_object_h = stdbuff_h...
    + rbtn_h + minbuff_h...
    + rbtn_h + stdbuff_h;

operationpanel_h=...
    stdbuff_h...
    + pushbutton_h + minbuff_h...
    + pushbutton_h...
    + stdbuff_h...
    + operationpanel_object_h...
    + operationpanel_mode_h;

%Widths
stdbuff_w=20;
element_w=130;
panel_w=element_w+2*stdbuff_w;               %Buffer is on left and right
stdbuff_w=stdbuff_w-2;                       %InnerPosition of panels is 2 pixels away from the Position property

%From Left
panel_l=buff.w;
element_l=stdbuff_w;                         %This is relative to the panel

%From bottom
viewpanel_b=buff.h;

view_chnrb_b=stdbuff_h+view_relintrb_h+elementsep_h;

view_shift_b=view_chnrb_b+view_chnrb_h+elementsep_h;

view_intrange_b=view_shift_b...
    + txtbx_h + txt_h + minbuff_h...
    + elementsep_h;

operationpanel_b=viewpanel_b+viewpanel_h+elementsep_h+elementsep_h;

newaxonbtn_b=stdbuff_h;

savebutton_b=newaxonbtn_b...
    + pushbutton_h + minbuff_h;

operationpanel_object_b=savebutton_b...
    + pushbutton_h + stdbuff_h;

operationpanel_mode_b = operationpanel_object_b...
    + operationpanel_object_h;

xyaxis_w=min([fi.H-1.5*buff.h,fi.W-panel_l-panel_w-buff.h]);
operationpanel_b=max([operationpanel_b,xyaxis_w+buff.h-operationpanel_h]);

fi.H=1.5*buff.h+xyaxis_w;
fi.W=min([fi.W,3*buff.w+buff.h+panel_w+xyaxis_w]);
hf.Position=[fi.L,fi.B,fi.W,fi.H];
